### ISSUE TITLE
Test credentials

### ISSUE THREAD

**Issue by dandv** [Preposterous/twitter-lite#11]
Useful for adding end-to-end tests, e.g. that both `client.get('statuses/show/964185606803853314')` and `client.get('statuses/lookup', {
  id: '964185606803853314,965299128162029568',
  map: true,
})` return the same tweet. (These are tests I had run locally before my #10 PR).

**Comment by peterpme** [comment]
:wave: hey this is an awesome idea! @dandv 

Do you have any idea how to set this up without having a nefarious individual steal the vars?

**Comment by peterpme** [comment]
Created test credentials and added them to travis. Great idea, thanks!
