### ISSUE TITLE
Unable to do post request to oauth/request_token

### ISSUE THREAD

**Issue by ongspxm** [Preposterous/twitter-lite#12]
I have been trying to do 

```
client.post("oauth/request_token", {oauth_callback:secret.callbackURL}).then(function(res){
    console.log(res);
});
```

but keep getting the following error `{ errors: [ { code: 89, message: 'Invalid or expired token.' } ] }`

any help?

**Comment by peterpme** [comment]
Hey @ongspxm,

Does it work with a GET request? It sounds like the library is working but your token is expired. Are you setting the correct variables?

Do you want to put up an entire example?

Thanks!

**Comment by peterpme** [comment]
Hey @ongspxm 

any luck?

**Comment by ongspxm** [comment]
On the twitter dashboard, it shows `
https://api.twitter.com/oauth/request_token` as the url to perform all the
oauth steps.

But in the script, `https://${subdomain}.twitter.com/1.1` is given as the
base url, this translates into `api.twitter.com/1.1` during runtime. This
is correct for API calls after the access token is received.

Currently, i am using another library to complete the process of retrieving
a access token. Are there plans to include the process in `twitter-lite`?

Maybe i have missed something out, is it possible to obtain go through the
twitter authentication process using twitter lite?

**Comment by peterpme** [comment]
Hey @ongspxm,

Right now we don't support `request_token` URL but soon in the future we will! If you have any experience in authenticating users any help would be appreciated.

Thanks!

**Comment by ongspxm** [comment]
right, I will try working on it, will ask for help if i have any problem.
