### ISSUE TITLE
Help write documentation for Obtaining Bearer Token for App-based Auth

### ISSUE THREAD

**Issue by peterpme** [Preposterous/twitter-lite#5]

**Comment by crlssn** [comment]
Hey, you could do someting similar to...
```javascript
const basicToken = Buffer.from(`${process.env.TWITTER_CONSUMER_KEY}:${process.env.TWITTER_CONSUMER_SECRET}`).toString('base64')

let response = await axios.post('https://api.twitter.com/oauth2/token', 'grant_type=client_credentials', {
  headers: {
    Authorization: `Basic ${basicToken}`,
    ContentType: 'application/x-www-form-urlencoded;charset=UTF-8'
  }
})

const bearerToken = response.data.access_token
const query = 'twitter'

response = await axios.get(`https://api.twitter.com/1.1/search/tweets.json?q=${query}&result_type=popular`, {
  headers: {
    Authorization: `Bearer ${bearerToken}`
  }
})
```

Notice that I can't use your current helper methods since you inject `.json` without the possibility to add a search query. I might add a pull request later but thought I comment here incase someone is struggling to make it work.

**Comment by peterpme** [comment]
Hey @crlssn 

A pull request would be amazing!

Thank you so much for adding this comment.

I was even thinking about letting users set their own transport method, ie: `axios`, `fetch`, `request`, etc and that would make the whole streaming thing a lot easier to manage :)

Thanks again!

**Comment by dandv** [comment]
Would love to see docs for got to get the bearer token; or, we could make authentication easier via a boolean parameter to the constructor, distinguishing between user and app. [Twit does this](https://github.com/ttezel/twit#twit-api), and it seems less confusing.
